import{a as g,S as y,G as h,i as m}from"./assets/vendor-tnS95ulj.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const L=g.create({baseURL:"https://pixabay.com/api/",params:{key:"53374429-639c77152d70b3fe75f006246",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0}});function v(r){return L.get("",{params:{q:r}})}let D={galleryElem:document.querySelector(".gallery")};const{galleryElem:l}=D;let n=null;function b({webformatURL:r,largeImageURL:s,tags:o,likes:i,views:e,comments:t,downloads:a}){let f=o.split(",").slice(0,3);return`
  <li class="list-item">
        <div class="item-container">
        <a href="${s}" class="">
          <img src="${r}" alt="${f}" class="item-img">
          </a>
          <div class="desc-container">
            <p class="item-title">Likes <span item-num>${i}</span></p>
            <p class="item-title">Views <span item-num>${e}</span></p>
            <p class="item-title">Comments <span item-num>${t}</span></p>
            <p class="item-title">Downloads <span item-num>${a}</span></p>
          </div>
        </div>
      </li>`}function w(r){const s=r.map(b).join(""),o=new y(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250,overlayOpacity:.85});return l.innerHTML=s,o.refresh(),s}function u(){l.innerHTML=""}function O(){n||(l.insertAdjacentHTML("beforebegin",'<div class="loader"></div>'),n=document.querySelector(".loader"))}function E(){n&&setTimeout(()=>{n.remove(),n=null},700)}function d(){n&&setTimeout(()=>{n.remove(),n=null},5e3)}function p(){new h({element:"#granim-canvas",name:"granim",opacity:[1,1],states:{"default-state":{gradients:[["#834D9B","#D04ED6"],["#1CD8D2","#93EDC7"]]}}})}const S={form:document.querySelector(".form")},{form:c}=S;document.addEventListener("DOMContentLoaded",()=>{p()});c.addEventListener("submit",r=>{r.preventDefault(),O();const o=new FormData(c).get("search-text");if(o.includes(" "))return d(),u(),c.reset(),m.show({messageSize:"20",message:"Будь ласка введіть назву фото!",position:"center",close:!0,closeOnEscape:!0,theme:"light",color:"yellow"});u(),c.reset(),v(o).then(i=>{const e=i.data.hits;if(e.length===0)return Promise.reject();w(e),p(),E()}).catch(()=>{d(),m.show({messageSize:"20",message:"На жаль, немає зображень, що відповідають вашому пошуковому запиту. Спробуйте ще раз!",position:"center",close:!0,closeOnEscape:!0,theme:"light",color:"orange"})})});
//# sourceMappingURL=index.js.map
