import{a as g,S as y,G as h,i as l}from"./assets/vendor-tnS95ulj.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const L=g.create({baseURL:"https://pixabay.com/api/",params:{key:"53374429-639c77152d70b3fe75f006246",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0}});function v(i){return L.get("",{params:{q:i}})}let D={galleryElem:document.querySelector(".gallery"),loader:document.querySelector(".loader")};const{galleryElem:d,loader:o}=D;console.log(o);function b({webformatURL:i,largeImageURL:s,tags:r,likes:a,views:e,comments:t,downloads:n}){let f=r.split(",").slice(0,3);return`
  <li class="list-item">
        <div class="item-container">
        <a href="${s}" class="">
          <img src="${i}" alt="${f}" class="item-img">
          </a>
          <div class="desc-container">
            <p class="item-title">Likes <span item-num>${a}</span></p>
            <p class="item-title">Views <span item-num>${e}</span></p>
            <p class="item-title">Comments <span item-num>${t}</span></p>
            <p class="item-title">Downloads <span item-num>${n}</span></p>
          </div>
        </div>
      </li>`}function w(i){const s=i.map(b).join(""),r=new y(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250,overlayOpacity:.85});return d.innerHTML=s,r.refresh(),s}function m(){d.innerHTML=""}function O(){o.classList.contains("isActive")||o.classList.add("isActive")}function E(){o.classList.contains("isActive")&&setTimeout(()=>{o.classList.remove("isActive")},700)}function u(){o.classList.contains("isActive")&&setTimeout(()=>{o.classList.remove("isActive")},5e3)}function p(){new h({element:"#granim-canvas",name:"granim",opacity:[1,1],states:{"default-state":{gradients:[["#834D9B","#D04ED6"],["#1CD8D2","#93EDC7"]]}}})}const A={form:document.querySelector(".form")},{form:c}=A;document.addEventListener("DOMContentLoaded",()=>{p()});c.addEventListener("submit",i=>{i.preventDefault(),O();const r=new FormData(c).get("search-text").trim();if(r==="")return u(),m(),c.reset(),l.show({messageSize:"20",message:"Будь ласка введіть назву фото!",position:"center",close:!0,closeOnEscape:!0,theme:"light",color:"yellow"});m(),c.reset(),v(r).then(a=>{const e=a.data.hits;if(e.length===0)return Promise.reject();w(e),p(),E()}).catch(()=>{u(),l.show({messageSize:"20",message:"На жаль, немає зображень, що відповідають вашому пошуковому запиту. Спробуйте ще раз!",position:"center",close:!0,closeOnEscape:!0,theme:"light",color:"orange"})})});
//# sourceMappingURL=index.js.map
